secretsprovider: awskms://alias/pulumi-secrets-prod?region=ap-northeast-2
encryptedkey: AQICAHhrkDrAC78l9phNpJsf11VsafO8k88Fs6NYm5VUW4hX1gF4XMvJGz+/ckyXX4FCaQsbAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5Ya2FyWsG5LHhM4QAgEQgDs5885GU+AkPiH/JUFUNsucRvYIsKMoOI226GMY/GV8XNNnSWfwCCBXV4rPcpJ1RtmClAOAWutjqFXhJw==
config:
  aws:region: ap-northeast-2
  aws:defaultTags:
    tags:
      Service: officeagent
      Component: officeagent-pii-guard
      Environment: prod
  officeagent-pii-guard:domain:
    fqdn: pii-guard-local.officeagent.kr
    hostedZoneName: officeagent.kr
    hostedZoneId: Z04331861UDPHXIBOW1BF
  officeagent-pii-guard:crossAccount:
    roleArn: arn:aws:iam::037684266277:role/pii-guard-cross-account-route53
    externalId: pii-guard-cross-account
    region: ap-northeast-2
  officeagent-pii-guard:site:
    distPath: ../../dist
    bucketName: officeagent-pii-guard-prod
